fixes

diff --git a/.github/workflows/deploy-todo-list.yml b/.github/workflows/deploy-todo-list.yml
--- a/.github/workflows/deploy-todo-list.yml
+++ b/.github/workflows/deploy-todo-list.yml
@@ -58,18 +58,25 @@ jobs:
             CONTAINER_ID=$(docker ps -q -f "publish=8000")
             if [ ! -z "$CONTAINER_ID" ]; then
               echo "A container is already running on port 8000. Stopping the existing container."
+            
+              # Step 1: Backup db.sqlite3 from the running container to the host
+              echo "Backing up the db.sqlite3 from the container to the host"
+              docker cp $CONTAINER_ID:/db.sqlite3 /home/ec2-user/todo-app/db.sqlite3 || { echo 'Failed to backup db.sqlite3'; exit 1; }
+            
+              # Step 2: Stop and remove the old container
               docker stop $CONTAINER_ID || { echo 'Failed to stop the existing container'; exit 1; }
               docker rm $CONTAINER_ID || { echo 'Failed to remove the existing container'; exit 1; }
             else
               echo "No container is running on port 8000."
             fi
-      
+            
+            # Step 3: Start a new container
             echo "Starting a new container with the latest image"
-            docker run -d -p 8000:8000 --name todo-app \
+            docker run -d -p 8000:8000 \
               -v /home/ec2-user/todo-app/db.sqlite3:/db.sqlite3 \
-              -v /home/ec2-user/todo-app/staticfiles:/staticfiles \
-              724772048392.dkr.ecr.us-east-1.amazonaws.com/image-repository:latest || { echo 'Docker run failed'; exit 1; }
-
-      
+              --name todo-app 724772048392.dkr.ecr.us-east-1.amazonaws.com/image-repository:latest || { echo 'Docker run failed'; exit 1; }
+            
+            # Step 4: Confirm the app is accessible
             echo "Access the application on http://ec2-3-140-188-18.us-east-2.compute.amazonaws.com:8000"
+
       
