fixed echo line in CD part, public ip of deployment server is configured as git actions secret, so echoing it in script doesn't display the public ip so replacing it by public dns

diff --git a/.github/workflows/deploy-todo-list.yml b/.github/workflows/deploy-todo-list.yml
--- a/.github/workflows/deploy-todo-list.yml
+++ b/.github/workflows/deploy-todo-list.yml
@@ -54,41 +54,37 @@ jobs:
             echo "Pull the latest image from ECR"
             docker pull 724772048392.dkr.ecr.us-east-1.amazonaws.com/image-repository:latest
       
-            echo "Check if a container is already running on port 8000"
-            CONTAINER_ID=$(docker ps -q -f "publish=8000")
+      echo "Check if a container is already running on port 8000"
+      CONTAINER_ID=$(docker ps -q -f "publish=8000")
 
-            # Step 1: If a container is running on port 8000, we will handle it
-            if [ ! -z "$CONTAINER_ID" ]; then
-              echo "A container is already running on port 8000. Stopping the existing container."
+- name: CD. Pull the image from ECR and Deploy the app on the deployment server
+  uses: appleboy/ssh-action@v1.2.0
+  with:
+    host: ${{ secrets.HOST }}
+    username: ${{ secrets.USERNAME }}
+    key: ${{ secrets.KEY }}
+    port: ${{ secrets.PORT }}
+    script: |
+      echo "Login to ECR repository"
+      aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 724772048392.dkr.ecr.us-east-1.amazonaws.com
 
-              # Backup the db.sqlite3 from the running container to the host (before stopping it)
-              echo "Backing up db.sqlite3 from the container to the host"
-              docker cp $CONTAINER_ID:/db.sqlite3 /home/ec2-user/todo-app/db.sqlite3 || { echo 'Failed to backup db.sqlite3'; exit 1; }
+      echo "Pull the latest image from ECR"
+      docker pull 724772048392.dkr.ecr.us-east-1.amazonaws.com/image-repository:latest
 
-              # Stop the existing container
-              docker stop $CONTAINER_ID || { echo 'Failed to stop the existing container'; exit 1; }
+      echo "Check if a container is already running on port 8000"
+      CONTAINER_ID=$(docker ps -q -f "publish=8000")
+      if [ ! -z "$CONTAINER_ID" ]; then
+        echo "A container is already running on port 8000. Stopping the existing container."
+        docker stop $CONTAINER_ID || { echo 'Failed to stop the existing container'; exit 1; }
+        docker rm $CONTAINER_ID || { echo 'Failed to remove the existing container'; exit 1; }
+      else
+        echo "No container is running on port 8000."
+      fi
 
-              # Force remove the existing container to release the container name (todo-app)
-              docker rm -f $CONTAINER_ID || { echo 'Failed to remove the existing container'; exit 1; }
-            else
-              echo "No container is running on port 8000."
-            fi
+      echo "Starting a new container with the latest image"
+      docker run -d -p 8000:8000 --name todo-app 724772048392.dkr.ecr.us-east-1.amazonaws.com/image-repository:latest || { echo 'Docker run failed'; exit 1; }
 
-            # Step 2: Ensure that db.sqlite3 exists from the previous container backup (on the host)
-            if [ ! -f /home/ec2-user/todo-app/db.sqlite3 ]; then
-              echo "Error: No db.sqlite3 file found on the host. Cannot proceed with the new container."
-              exit 1
-            fi
-
-            # Step 3: Start the new container with the latest image and mount the backed-up db.sqlite3
-            echo "Starting a new container with the latest image and mounting the database file"
-            docker run -d -p 8000:8000 \
-              -v /home/ec2-user/todo-app/db.sqlite3:/db.sqlite3 \
-              --name todo-app 724772048392.dkr.ecr.us-east-1.amazonaws.com/image-repository:latest || { echo 'Docker run failed'; exit 1; }
-
-            # Step 4: Confirm the app is accessible
-            echo "Access the application on http://ec2-3-140-188-18.us-east-2.compute.amazonaws.com:8000"
-
+      echo "Access the application on http://ec2-3-140-188-18.us-east-2.compute.amazonaws.com:8000"
 
 
 
