fixed echo line in CD part, public ip of deployment server is configured as git actions secret, so echoing it in script doesn't display the public ip so replacing it by public dns

diff --git a/.github/workflows/deploy-todo-list.yml b/.github/workflows/deploy-todo-list.yml
--- a/.github/workflows/deploy-todo-list.yml
+++ b/.github/workflows/deploy-todo-list.yml
@@ -53,40 +53,21 @@ jobs:
       
             echo "Pull the latest image from ECR"
             docker pull 724772048392.dkr.ecr.us-east-1.amazonaws.com/image-repository:latest
+
+            echo "Check if a container is already running on port 8000"
+            CONTAINER_ID=$(docker ps -q -f "publish=8000")
+            if [ ! -z "$CONTAINER_ID" ]; then
+              echo "A container is already running on port 8000. Stopping the existing container."
+              docker stop $CONTAINER_ID || { echo 'Failed to stop the existing container'; exit 1; }
+              docker rm $CONTAINER_ID || { echo 'Failed to remove the existing container'; exit 1; }
+            else
+              echo "No container is running on port 8000."
+            fi
       
-      echo "Check if a container is already running on port 8000"
-      CONTAINER_ID=$(docker ps -q -f "publish=8000")
-
-- name: CD. Pull the image from ECR and Deploy the app on the deployment server
-  uses: appleboy/ssh-action@v1.2.0
-  with:
-    host: ${{ secrets.HOST }}
-    username: ${{ secrets.USERNAME }}
-    key: ${{ secrets.KEY }}
-    port: ${{ secrets.PORT }}
-    script: |
-      echo "Login to ECR repository"
-      aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 724772048392.dkr.ecr.us-east-1.amazonaws.com
-
-      echo "Pull the latest image from ECR"
-      docker pull 724772048392.dkr.ecr.us-east-1.amazonaws.com/image-repository:latest
-
-      echo "Check if a container is already running on port 8000"
-      CONTAINER_ID=$(docker ps -q -f "publish=8000")
-      if [ ! -z "$CONTAINER_ID" ]; then
-        echo "A container is already running on port 8000. Stopping the existing container."
-        docker stop $CONTAINER_ID || { echo 'Failed to stop the existing container'; exit 1; }
-        docker rm $CONTAINER_ID || { echo 'Failed to remove the existing container'; exit 1; }
-      else
-        echo "No container is running on port 8000."
-      fi
-
-      echo "Starting a new container with the latest image"
-      docker run -d -p 8000:8000 --name todo-app 724772048392.dkr.ecr.us-east-1.amazonaws.com/image-repository:latest || { echo 'Docker run failed'; exit 1; }
-
-      echo "Access the application on http://ec2-3-140-188-18.us-east-2.compute.amazonaws.com:8000"
-
-
+            echo "Starting a new container with the latest image"
+            docker run -d -p 8000:8000 --name todo-app 724772048392.dkr.ecr.us-east-1.amazonaws.com/image-repository:latest || { echo 'Docker run failed'; exit 1; }
+      
+            echo "Access the application on http://3.140.188.18:8000"
 
 
       
